### PR TITLE
Map

### PR DESCRIPTION
**Pull request by tomwayson**
Replaces hero background image w/ the actual web map that powers the search:

image

TODO: 
- [ ] zoom map to address once it is selected
- [ ] make the example web maps pretty (turn layers on/off at scales, etc)
- [ ] prob need to add options like no scroll wheel zooming when initializing map

### CODE REVIEW

**Comment by tomwayson** [comment]
I'd rather re-do this using https://github.com/Esri/ember-esri-loader, so for now don't merge this.

**Comment by MarkhamShofner** [comment]
@tomwayson I've got a day or two this sprint (waiting on comps for new hub umbrella) to work on MyStreet, and am kicking the tires on upgrades/updates. Should I give the ember-esri-loader a crack (once I finish up some other things), or do you still want to knock that part out?

**Comment by tomwayson** [comment]
If you want to give emebr-esri-loader a try, that'd be fantastic. My idea was that we would only load the JSAPI if the `showMap` option was enabled for that app  - that would require changing the current template, etc to add that option.

I can work w/ you on this.

**Comment by MarkhamShofner** [comment]
Ok sounds good. Need to do some other fiddling to get the app up to scratch in other areas. Will reach out if/when I have questions.

**Comment by tomwayson** [comment]
If you're messing around in the config area at all, adding the `showMap` property (default to false) would be a big jumpstart to this.

**Comment by MarkhamShofner** [comment]
closing. see https://github.com/Esri/MyStreet/pull/16 for update PR

**Pull request closed without merging**
