### PR TITLE
Mappy

### PR DESCRIPTION
**Pull request by MarkhamShofner**
some current issues:
- address search full row overrides a decent amount of the map functionality (ie can't + or - with the zoom interface, or touch the map portions of the address search row)
- Address search shifts slightly on search

But let me know the general structure. Minor things can be cleaned up / adjusted later.

### CODE REVIEW

**Comment by tomwayson** [comment]
FYI - copying over these TODOs from #12 cause they're still needed w/ this PR:

- [ ] zoom map to address once it is selected
- [ ] make the example web maps pretty (turn layers on/off at scales, etc)
- [ ] prob need to add options like no scroll wheel zooming when initializing map

**Comment by tomwayson** [comment]
oh and tests are failing like it's going out of fashion, but for me that's also true on master (see #19)

**Comment by tomwayson** [comment]
@MarkhamShofner what's the deal w/ this?

**Comment by MarkhamShofner** [comment]
@tomwayson Looking to close it out before the end of this sprint. Have a version working locally but when deploying to `surge`, `ember-esri-loader` is causing issues.

**Pull request merged**
